# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/ti/panda/extract-files.sh - DO NOT EDIT


# All the blobs necessary for panda
PRODUCT_COPY_FILES += \
    vendor/ti/panda/proprietary/pvrsrvinit:system/vendor/bin/pvrsrvinit \
    vendor/ti/panda/proprietary/libEGL_POWERVR_SGX540_120.so:system/vendor/lib/egl/libEGL_POWERVR_SGX540_120.so \
    vendor/ti/panda/proprietary/libGLESv1_CM_POWERVR_SGX540_120.so:system/vendor/lib/egl/libGLESv1_CM_POWERVR_SGX540_120.so \
    vendor/ti/panda/proprietary/libGLESv2_POWERVR_SGX540_120.so:system/vendor/lib/egl/libGLESv2_POWERVR_SGX540_120.so \
    vendor/ti/panda/proprietary/gralloc.omap4.so:system/vendor/lib/hw/gralloc.omap4.so \
    vendor/ti/panda/proprietary/libglslcompiler.so:system/vendor/lib/libglslcompiler.so \
    vendor/ti/panda/proprietary/libIMGegl.so:system/vendor/lib/libIMGegl.so \
    vendor/ti/panda/proprietary/libpvr2d.so:system/vendor/lib/libpvr2d.so \
    vendor/ti/panda/proprietary/libpvrANDROID_WSEGL.so:system/vendor/lib/libpvrANDROID_WSEGL.so \
    vendor/ti/panda/proprietary/libPVRScopeServices.so:system/vendor/lib/libPVRScopeServices.so \
    vendor/ti/panda/proprietary/libsrv_init.so:system/vendor/lib/libsrv_init.so \
    vendor/ti/panda/proprietary/libsrv_um.so:system/vendor/lib/libsrv_um.so \
    vendor/ti/panda/proprietary/libusc.so:system/vendor/lib/libusc.so